### ISSUE TITLE
should moodle fullname() api be used

### ISSUE THREAD

**Issue by danmarsden** [academic-moodle-cooperation/moodle-mod_consentform#3]
https://github.com/academic-moodle-cooperation/moodle-mod_consentform/blob/master/classes/consentform_export.php#L58

might be better to do fullname($USER) there - many organisations will have configured moodle to display names differently from firstname, lastname.

**Comment by mkemmerling** [comment]
Fixed in master branch. Version 3.11.1 coming soon.
