### ISSUE TITLE
custom action handling should implement sesskey checks

### ISSUE THREAD

**Issue by danmarsden** [academic-moodle-cooperation/moodle-mod_consentform#4]
https://github.com/academic-moodle-cooperation/moodle-mod_consentform/blob/master/listusers.php#L50

see:
https://docs.moodle.org/dev/Security:Cross-site_request_forgery#What_you_need_to_do_in_your_code

**Comment by danmarsden** [comment]
I suspect this file should implement them too:
https://github.com/academic-moodle-cooperation/moodle-mod_consentform/blob/master/setcontrol.php

**Comment by mkemmerling** [comment]
Fixed in master branch. Version 3.11.1 coming soon.
