### ISSUE TITLE
The plugin Environment Ribbons overlaps the consent in course overview

### ISSUE THREAD

**Issue by acquaalta** [academic-moodle-cooperation/moodle-mod_consentform#8]
Hi,
We discovered this strange bug that happens when [the plugin "Environment Ribbons"](https://moodle.org/plugins/tool_ribbons) is active and when the option "Agreement in course overview" is active in the consent form instance. Please see the screenshot below:

![cfvser_bug](https://user-images.githubusercontent.com/51836675/228653916-d77ddbc2-eda6-448e-98ee-b084e17baff5.png)

As you can see, the ribbon overlaps the consent form. Even if it's something that can be or even should be fixed on the "Environment Ribbons" end, is it something that be fixed on your end, in the "Consent Form" plugin? The creator of the "Environment Ribbons" didn't release an official version of the plugin for a long time, and not too responsive.

Thanks, even just for reading this bug report.

**Comment by bluetom** [comment]
Hi,
the inline consent form is technically an iframe and the moodle page type it uses shows this ribbon. I will have a look into this plugin.

**Comment by acquaalta** [comment]
Thanks a lot :-)

**Comment by bluetom** [comment]
This would be a quick and dirty but not dangerous fix:

Go to "Site administration" - "Appearance" - "Themes" and choose your theme. Go to "Advanced Settings".
In the field "Raw SCSS" fill in:

`body#page-mod-consentform-confirmation #tool-ribbons-ribbon-1 {display:none !important;}`

Save changes and purge the caches -> Done.

**Comment by acquaalta** [comment]
Thanks a lot :-)
I tested the fix and it seems to work.
