### ISSUE TITLE
Consent Form - A site administrator can't see the course modules

### ISSUE THREAD

**Issue by acquaalta** [academic-moodle-cooperation/moodle-mod_consentform#9]
Hi,
Moodle version: 4.1.3
Plugin version: Release v4.1.1

We discovered that an admin that is not a teacher in a course can't see the course module in the "Consent Form" activity.
Is that intentional?

Thanks

**Comment by bluetom** [comment]
Not really. Although I am always admin in my moodle installations I never came across this problem because I was always enrolled as a teacher in my test courses. I will fix this in the upcoming consentform version 4.2...
BR,
Thomas

**Comment by acquaalta** [comment]
Thanks :-)

**Comment by bluetom** [comment]
Is fixed in Organizer Version 4.2.2.

**Comment by acquaalta** [comment]
Hi @bluetom,
1. Thanks for fixing the issue.
2. I assume that you meant that the issue is fixed in the version 4.2.2 of the "Consent Form" plugin. The "Organizer" plugin is another plugin that is maintained by "AMC Academic Moodle Cooperation".
3. Thanks again.
